### ISSUE TITLE
SkipCache is not actually skipping the cache.

### ISSUE THREAD

**Issue by victorcuena** [Cimpress/stereotype-client#14]
Use this line instead.
.get(BASE_URL + '/v1/templates/' + idTemplate + "?" + Math.random())

**Comment by ro-tex** [comment]
`Date.now()` changes every millisecond. I agree that `Math.random()` will be more, well, random but `Date.now()` should have the same effect.

Are you sure you're hitting the cache and that cache takes GET parameters into account?

**Comment by victorcuena** [comment]
My bad, the current behaviour also skips the cache. I will close the issue.
