### ISSUE TITLE
Method getTemplate succeeds when asking for template name that is empty string

### ISSUE THREAD

**Issue by rnowosielski** [Cimpress/stereotype-client#20]
When calling the following code

     let sc = new StereotypeClient(auth.getAccessToken())
      sc.getTemplate('')
        .then((template) => {
          console.log(template)
        }, (err) => {
          console.log(err)
        }
      )

I would expect the code the error and say that either such template does not exist or that the argument is invalid...

Instead the code succeeds and the object returned looks something like this:

`{templateType: "application/json", templateBody: [{"templateId" : "wefwef", "canCopy" : true,"canEdit":true"} ... }` 

which apparently is the result of getting all templates.

I am not sure if this is by design or not, but for sure is misleading.

**Comment by ro-tex** [comment]
I agree with the observation (call to bad template should fail but doesn't) but I the problem is not with the client. Stereotype responds with `200 OK` to this call and returns a list of all available (or accessible?) templates with their ids and access levels.

So, either this is a "feature" of Stereotype or it's a bug in Stereotype. It looks like it's intentional, though.

**Comment by ro-tex** [comment]
It actually looks like this is S3 functionality - when you pass an empty string it thinks you're pointing to the directory and gives you a directory listing. I'm having trouble reproducing this with `aws cli`. Kinda brain-dead at this point, so I'll leave it for tomorrow.

**Comment by rnowosielski** [comment]
The point of the client is to abstract the API and underlying technology for consumers in particular language.

https://hostname/v1/templates
https://hostname/v1/templates/

is one and the same endpoint which is he bulk endpoint returning templates available to the user

Whereas 
https://hostname/v1/templates/<templateid>
is meant to return the existing template

On the other hand if the client has separate methods for getting all templates and getting concrete template, but for reasons of string artihmetics (https://hostname/v1/templates/ concatenated with empty string) method for getting concrete template ends up calling the bulk endpoint. That I would call an extremely leaky abstraction. I think I would expect the method to get template to throw exception or something when called with empty string to make things easier for the user of the library to reason [it took me a longer moment to figure out what was hpoening]
