### ISSUE TITLE
Implement support for x-cimpress-rel-curies in the client

### ISSUE THREAD

**Issue by Igrom** [Cimpress/stereotype-client#5]
Stereotype now supports matching and replacing HTTP(S) web relations in the expanded payload with the new x-cimpress-rel-curies header. The mechanism presented is reminiscent of HAL+JSON curies, which are convenience replacements for URIs with shorter tokens. 

With this feature it is now possible to refer to normally uncuried resources in your templates. Previously, characters outside of the alphanumeric character class present in an URL would not allow for using them as tags in templates.

I would like to see the support for setting the x-cimpress-rel-curies header implemented, so that we may begin to make use of it.

**Comment by rnowosielski** [comment]
It seems that this got implemented in the meantime @Igrom ?
